### PR TITLE
Install platforms;android-32

### PR DESCRIPTION
**Pull request by meteorcloudy**
Try to fix https://github.com/bazelbuild/continuous-integration/issues/1588

### CODE REVIEW

**Comment by meteorcloudy** [comment]
We'll have to rebuild docker images + Windows VM image and install on macOS manually.

**Comment by sgowroji** [comment]
Hi @meteorcloudy, We are still seeing the error in flogger https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3350#018af351-1325-4b64-b7b7-dbb5e79bc2a4

```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-7g38/bazel-downstream-projects/flogger/google/BUILD:36:16: in javadoc_library rule //google:flogger_javadoc:
Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/c3ea6ac52571282244a9490118bd3aa5/external/google_bazel_common/tools/javadoc/javadoc.bzl", line 29, column 49, in _javadoc_library
		transitive_deps.append(dep[JavaInfo].transitive_deps)
Error: 'JavaInfo' value has no field or method 'transitive_deps'
```

**Comment by meteorcloudy** [comment]
Sorry, I haven't deployed the change yet.

**Comment by meteorcloudy** [comment]
The new android SDK has been installed. But Flogger now fails with a different error: https://buildkite.com/bazel/flogger/builds/2701#018d64f0-b10a-4a8c-92e6-beb4d40f5085

@sgowroji Can you please file an issue against Flogger?

**Comment by sgowroji** [comment]
@meteorcloudy  raised here google/flogger#373

**Pull request merged**
