### PR TITLE
Actually test Gerrit on ubuntu1804_java11

### LINKED ISSUE #325: Set up CI job for Gerrit on Java 10
Recently CI Job was set up for Gerrit on Java 9 (https://github.com/bazelbuild/continuous-integration/pull/322). To avoid regressions, CI Job for Java 10 should also be set up.

### PR DESCRIPTION
**Pull request by davido**
Closes #325.

### CODE REVIEW

**Comment by davido** [comment]
@philwo Can you take a look? I assume that the `JAVA_HOME` is: `/usr/lib/jvm/java-10-openjdk-amd64`. is that correct? The corresponding Gerrit change that added support for Vanilla Toolchain with using Vanilla Java Builder was merged today morning: [1].

[1] https://gerrit-review.googlesource.com/c/gerrit/+/193832

**Comment by philwo** [comment]
Hi @davido,

sorry for the late reply. We're using Azul Zulu on the machines, so the correct path would be: `/usr/lib/jvm/zulu-10-amd64`.

For reference:

```
philwo@bk-worker-ubuntu1804-java10-bm37:~$ ls -l /usr/lib/jvm/
total 4
drwxr-xr-x 10 root root 4096 Oct 22 09:58 zulu-10-amd64
```

Otherwise LGTM!

**Comment by davido** [comment]
> We're using Azul Zulu on the machines, so the correct path would be: /usr/lib/jvm/zulu-10-amd64.

Done.

**Comment by davido** [comment]
@philwo Note, that on Bazel 0.19.0, we could simplify the integration with recent Java versions, see: [1]. That's because `absolute_javabase` and `toolchain_vanilla` are part of Bazel's "tools/jdk" package now.

Also, do you have already Java 11 on Buildkite CI environment? In that case we could jump directly to Java 11 and skip Java 10 altogether.

* [1] https://gerrit-review.googlesource.com/c/gerrit/+/202830

**Comment by philwo** [comment]
Hi @davido,

sorry for not getting back to this earlier. I just came back from parental leave and am catching up with stuff.

Is this fine to merge?

> Also, do you have already Java 11 on Buildkite CI environment up and running? In that case we could jump directly to Java 11 and skip Java 10 altogether.

We still don't have support for Java 11 yet, but @meisterT might know what our plans are for that. Maybe Bazel already supports it and we just have to add it to our CI, in which case I'll happily do that.

**Comment by davido** [comment]
> We still don't have support for Java 11 yet, but @meisterT might know what our plans are for that.

Let's say t will take quite some time (years?) to make Bazel natively support Java 11, see https://github.com/bazelbuild/bazel/issues/6245. In that light, wouldn't it make sense to independently install Java 11 on Bazel CI environment and ensure that at least 2 projects: Gerrit and Bazel itself, (or just Gerrit, if you don't care that Bazel can be built with Java 11, we do care, though) can be built with Java 11 using VanillaJavaBuilder?

```
  $ bazel build \
    --define=ABSOLUTE_JAVABASE=/usr/lib64/jvm/java-11 \
    --host_javabase=@bazel_tools//tools/jdk:absolute_javabase \
    --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla \
    --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla \
    :release
```

**Comment by davido** [comment]
> I'll upgrade the embedded JDK to JDK11 soonish

By this you mean on Bazel CI or in Bazel itself (native support for JDK 11, that is tracked in bazelbuild/bazel#6245)?

**Comment by meisterT** [comment]
I mean the embedded JDK in Bazel, see #6592

**Comment by philwo** [comment]
> Install Java 11 on Bazel CI

I'll get that done ASAP.

**Comment by philwo** [comment]
Support for the ubuntu1804_java11 platform has been added: https://github.com/bazelbuild/continuous-integration/commit/9f9c1897ba1976572af9dd9da1e721c0203a7785 and https://github.com/bazelbuild/continuous-integration/commit/bc7ae6eb84173335cb5fe0df877354c9fb1b05a3

The absolute path to the Azul Zulu 11 JDK is: `/usr/lib/jvm/zulu-11-amd64`

**Comment by davido** [comment]
Thanks @philwo. That's awesome.

Let me adjust this PR to use Azul Zulu 11 JDK with `VanillaJavaToolchain`. Can you then merge this so that Gerrit Code Review will be the very first project that is built with JDK 11 on Bazel CI?

**Comment by davido** [comment]
Great news, thank you! I have just realized, that Bazel can also be built with Java 11, so that something like this worked:

```
  $ b10 build --define=ABSOLUTE_JAVABASE=/home/davido/pgm/jdk-11 --host_javabase=@bazel_tools//tools/jdk:absolute_javabase --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla src:bazel-dev
```

Then to make use of it, I added this line to `~/.bazelrc`:

```
$ tail -1 ~/.bazelrc
startup --server_javabase=/home/davido/pgm/jdk-11
```

And then I tested to build gerrit with Bazel-built-with-JDK11 and compared it building gerrit Gerrit with vanilla bazel 0.22rc2. The results are below:

```
  $ time b10 build --define=ABSOLUTE_JAVABASE=/home/davido/pgm/jdk-11 --host_javabase=@bazel_tools//tools/jdk:absolute_javabase --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla :release
[...]
  INFO: From Compiling 641 JavaScript files to polygerrit-ui/app/polygerrit_ui_closure_bin.js:
WARNING - Failed to resolve sourcemap at bazel-out/k8-fastbuild/bin/polygerrit-ui/app/web-animations-next-lite.min.js.map: bazel-out/k8-fastbuild/bin/polygerrit-ui/app/web-animations-next-lite.min.js.map
  Codes: SOURCEMAP_RESOLVE_FAILED

0 error(s), 1 warning(s)

Target //:release up-to-date:
  bazel-bin/release.war
INFO: Leaving sandboxfs mounted because of --sandbox_debug
INFO: Elapsed time: 238.288s, Critical Path: 121.96s
INFO: 1435 processes: 612 linux-sandbox, 7 local, 816 worker.
INFO: Build completed successfully, 2210 total actions

real	3m58.359s
user	0m0.061s
sys	0m0.068s
```

then I clean everything, including tests and re-run the build with vanilla Bazel 0.22-rc2:

```
  $ bazel version
Build label: 0.22.0rc2

  $ time bazel build :release
[...]

INFO: From Compiling 641 JavaScript files to polygerrit-ui/app/polygerrit_ui_closure_bin.js:
WARNING - Failed to resolve sourcemap at bazel-out/k8-fastbuild/bin/polygerrit-ui/app/web-animations-next-lite.min.js.map: bazel-out/k8-fastbuild/bin/polygerrit-ui/app/web-animations-next-lite.min.js.map
  Codes: SOURCEMAP_RESOLVE_FAILED

0 error(s), 1 warning(s)

Target //:release up-to-date:
  bazel-bin/release.war
INFO: Elapsed time: 288.698s, Critical Path: 101.78s
INFO: 1435 processes: 612 linux-sandbox, 7 local, 816 worker.
INFO: Build completed successfully, 2210 total actions

real	4m48.769s
user	0m0.056s
sys	0m0.075s
```

Do we have an explanation, why it takes 3m58.359s to build gerrit (with cold cache) with Bazel@JDK11 and 4m48.769s to build gerrit (with cold cache) with vanilla Bazel? 

Is it only because of Error Prone integration and other neat features that vanilla Bazel offers?

**Comment by philwo** [comment]
> Do we have an explanation, why it takes 3m58.359s to build gerrit (with cold cache) with Bazel@JDK11 and 4m48.769s to build gerrit (with cold cache) with vanilla Bazel?

I think the VanillaJavaBuilder is faster than the full-featured one with Error Prone etc., but I don't think anyone ever benchmarked how much the difference is. It's possible that this is the reason, yes.

**Pull request merged**
