### PR TITLE
Add rules_android_ndk CI

### PR DESCRIPTION
**Pull request by keith**
https://github.com/bazelbuild/rules_android_ndk/pull/7

### CODE REVIEW

**Comment by meteorcloudy** [comment]
This is only for the downstream pipeline configuration. You probably want to add configuration for rules_android_ndk in https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/terraform/bazel/main.tf first.

**Comment by keith** [comment]
oops thanks, updated!

**Review by meteorcloudy — APPROVED** [review]
Thanks!

**Comment by meteorcloudy** [comment]
Pipeline created, but first run has some failures: https://buildkite.com/bazel/rules-android-ndk/builds/1#0183213d-758d-4ccd-a143-5c38d3ef303f

**Comment by meteorcloudy** [comment]
I'm disabling rules_andorid_ndk in downstream until the postsubmit is fixed.

**Pull request merged**
