### PR TITLE
Add missing '#' to mac/mac-service.sh.

### PR DESCRIPTION
**Pull request by philwo**

### CODE REVIEW

**Comment by ulfjack** [comment]
I don't have write access?

**Comment by philwo** [comment]
@ulfjack I'm not an admin of our GitHub org or this repo, so I can't grant write permissions. :( Damien can probably do it. I don't know who else, as GitHub doesn't seem to want to show me the list of admins.

Regarding how it happened, it was missed during a code review: https://bazel-review.googlesource.com/c/11557 and then not noticed later, because it didn't cause any actual harm (because the scripts here don't use set -e, so they just ignore the error :/).

**Comment by ulfjack** [comment]
Can you merge it yourself or do you also not have write access?

**Comment by dslomov** [comment]
jenkins test this please

**Comment by dslomov** [comment]
I do not have write permissions either. For gerrit workflow, one can only merge through gerrit.
I think there should be one of those cute little comments that would merge from here but I do not know them and they are not very discoverable.

**Comment by dslomov** [comment]
jenkins merge this

**Comment by dslomov** [comment]
nope :(

**Comment by dslomov** [comment]
I think Gerrit is the only way.

**Comment by philwo** [comment]
OK Google, merge this.

**Comment by philwo** [comment]
Resent using Gerrit, thus closing here.

**Pull request closed without merging**
