### PR TITLE
setup_mac.sh: Use Android SDK r24.4.1 and NDK r11c

### PR DESCRIPTION
**Pull request by philwo**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by philwo** [comment]
@damienmg Could you give this a quick look? I'll then use the script to bootstrap our reinstalled Mac Pro. :)

**Comment by damienmg** [comment]
This looks good, but we commit change through gerrit for this project.

**Comment by philwo** [comment]
OK, will resend via Gerrit. :)

**Pull request closed without merging**
