### PR TITLE
Update Android build-tools version to 30.0.0-rc4

### PR DESCRIPTION
**Pull request by ahumesky**

### CODE REVIEW

**Comment by philwo** [comment]
A few projects hardcode older versions of the build-tools:

- https://github.com/bazelbuild/examples/blob/master/android/firebase-cloud-messaging/WORKSPACE#L7
- https://github.com/bazelbuild/rules_jvm_external/blob/master/WORKSPACE#L6 (also in some of their WORKSPACE files in the `examples` folder)
- https://github.com/android/testing-samples/blob/master/WORKSPACE#L8
- https://github.com/google/google-authenticator-android/blob/master/WORKSPACE#L20

We tried to upgrade one of them to 29.x some time ago, but ran into issues: https://github.com/android/testing-samples/commit/a2f1e85fa30c92adf7897d559861ab801606e4d0

So, these projects will currently break if we remove the old build-tools versions unless they migrate to the newer one. Is that OK? Should we migrate them first?

**Comment by jin** [comment]
`sdkmanager` allows installing two versions of the build-tools. Bazel picks the latest version by default. Let's keep both versions so we don't have to migrate downstream projects?

**Comment by jin** [comment]
It looks like the Android rules and aapt2.exe from 29.0.3 aren't playing nice with each other on Windows:

```
Jun 09, 2020 12:24:04 PM java.util.stream.ForEachOps$ForEachOp$OfRef accept
--
  | SEVERE: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-hdpi-v4\abc_ab_share_pack_mtrl_alpha.9.png:
  | Command: external\androidsdk\build-tools\29.0.3\aapt2.exe\
  | compile\
  | -v\
  | --legacy\
  | -o\
  | C:\temp\android_resources_tmp3793697009167363287\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-hdpi-v4\abc_ab_share_pack_mtrl_alpha.9.png
  | Output:
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-hdpi-v4\abc_ab_share_pack_mtrl_alpha.9.png: note: compiling PNG.
  |  
```

https://buildkite.com/bazel/bazel-bazel-examples/builds/543#bc5415a1-52b2-48e1-9ba3-049713d998bd

**Comment by ahumesky** [comment]
Thanks Jin! I'm also fine with keeping whatever previous versions we need for now

**Comment by jin** [comment]
@ahumesky I think it's a much quicker fix to retain 28.0.2 and 29.0.3 build-tools in the configuration.

**Comment by philwo** [comment]
I'll edit the PR, merge it and then later roll out the changes in new VMs.

**Comment by philwo** [comment]
I'm rolling this forward with build-tools 30.0.1.

**Pull request merged**
