### PR TITLE
Enable verification for gerrit project

### PR DESCRIPTION
**Pull request by davido**

### CODE REVIEW

**Comment by davido** [comment]
//CC @meteorcloudy @hvadehra

**Comment by davido** [comment]
> Is the original issue in https://bugs.chromium.org/p/gerrit/issues/detail?id=16632 already resolved?

Yes, Error Prone bug pattern violations were addressed: severity level was demoted to warning.
Bazel version was updated to 6.1.2 and java_tools to v12.1.

**Comment by meteorcloudy** [comment]
Sounds great!

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
Once Gerrit is green in https://buildkite.com/bazel/bazel-at-head-plus-disabled, I'll merge this PR

**Comment by meteorcloudy** [comment]
And Gerrit is green: https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/1655 \o/

**Pull request merged**
