### PR TITLE
Release pipeline: switch to release branch/tag correctly

### PR DESCRIPTION
**Pull request by meteorcloudy**
Fixes https://github.com/bazelbuild/continuous-integration/issues/1077

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Testing this at:
for release candidate: https://buildkite.com/bazel-trusted/bazel-release/builds/208
for final release: https://buildkite.com/bazel-trusted/bazel-release/builds/207

**Comment by meteorcloudy** [comment]
Looks like the arm build still needs some tweak.

**Comment by meteorcloudy** [comment]
Looks like this PR works!
https://buildkite.com/bazel-trusted/bazel-release/builds/209
https://buildkite.com/bazel-trusted/bazel-release/builds/210
It passed for 4.0.0rc7, and failed for 3.7.2 with some other reason (I guess it's Bazel doesn't actually work for arm with 3.7.2?).

**Comment by philwo** [comment]
Nice, thank you Yun! It's strange though that 3.7.2 could not be successfully built on arm64...

I agree it's likely unrelated to this change, but I wonder why it worked in an earlier run of the Bazel 3.7.2 pipeline? 🤔

**Comment by philwo** [comment]
e.g. https://buildkite.com/bazel-trusted/bazel-release/builds/206#1628a4e2-ea99-43b0-8ccd-5f9ec7c6f292

**Comment by meteorcloudy** [comment]
> I agree it's likely unrelated to this change, but I wonder why it worked in an earlier run of the Bazel 3.7.2 pipeline? 🤔

Yeah! Just noticed that, is there any recent change to the arm machines? This is indeed strange.

**Comment by meteorcloudy** [comment]
I'm running the build inside the docker container on the arm1 machine.

**Comment by philwo** [comment]
> > I agree it's likely unrelated to this change, but I wonder why it worked in an earlier run of the Bazel 3.7.2 pipeline? 🤔
> 
> Yeah! Just noticed that, is there any recent change to the arm machines? This is indeed strange.

No, I haven't touched it since before my vacation...

Maybe it's an incrementality issue? We could try to wipe the state from the machine:

```sh
# This contains the Bazel output base etc.
rm -rf /var/lib/buildkite-agent/.cache/bazel

# This contains the Git working directory.
rm -rf /var/lib/buildkite-agent/builds/arm1-bazel-build/bazel-trusted/bazel-release
```

**Comment by meteorcloudy** [comment]
After removing the sources, the arm build now works for creating final release.
It might be caused by the fact we have two buildkite agents connected to the same machine.. @philwo is going to fix it.

**Review by philwo — APPROVED** [review]

**Pull request merged**
