### PR TITLE
Revert "Use rbe_autoconfig in BuildKiteCI"

### PR DESCRIPTION
**Pull request by xingao267**
Reverts bazelbuild/continuous-integration#551

This is breaking all rules build on RBE.

### CODE REVIEW

**Comment by xingao267** [comment]
cc @nlopezgi

**Comment by xingao267** [comment]
@fweikert Could you help merging this rollback PR. It's breaking all RBE builds on Buildkite.

**Comment by philwo** [comment]
@xingao267 Is the rollback safe, now that we already made all changes in the repos to use the new mechanism?

**Comment by xingao267** [comment]
Yes. It's fine except for bazel-toolchains, rules_docker (which I will fix as well) and bazel postsubmit (which I sent an internal rollback CL)

**Comment by xingao267** [comment]
The changes in other repos (rules_go, rules_nodejs, etc) are just updating the pin of bazel-toolchain and add extra load() and target in WORKSPACE. As long as we don't use those targets, it should be fine.

**Comment by philwo** [comment]
OK, let's merge this as soon as the internal rollback for the CL configuration for Bazel is in then!

**Comment by xingao267** [comment]
The internal CL's presubmit is red because of this. We should probably submit this one first.

**Pull request merged**
