### PR TITLE
Switch Bazel's CI repo off the deprecated docker_build rules.

### PR DESCRIPTION
**Pull request by mattmoor**

### CODE REVIEW

**Comment by mattmoor** [comment]
@damienmg Sending this sort of YOLO to let the CI setup test it for me.  I'll fix if something breaks.

**Comment by mattmoor** [comment]
@damienmg What version of Docker are you guys using on your CI setup?

**Comment by damienmg** [comment]
@mattmoor : 1.9.1 :/ We should update.

I believe we fixed the version of docker when we had the problem of docker 1.10 new images: https://github.com/bazelbuild/continuous-integration/blob/master/gce/ubuntu-15-10-docker.sh#L12

We can update the version of docker then do that change.

Btw for this repo we only accept change on gerrit right now :/ https://bazel.googlesource.com/continuous-integration.

**Comment by mattmoor** [comment]
We will see if my interest in seeing this happens outweighs my distaste for Gerrit, but for now consider this abandoned.

**Comment by damienmg** [comment]
Thanks I'll take over the PR as it is ready :)

**Comment by mattmoor** [comment]
LOL, I used `sed` :)

**Pull request closed without merging**
