### PR TITLE
Minor Bash improvements

### PR DESCRIPTION
**Pull request by Androbin**
Based on output of static analysis tool.

https://github.com/koalaman/shellcheck/wiki/SC2006
https://github.com/koalaman/shellcheck/wiki/SC2166
https://github.com/koalaman/shellcheck/wiki/SC2004
https://github.com/koalaman/shellcheck/wiki/SC2185

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ulfjack** [comment]
Yun, who has write access on this branch? Can we just merge this?

**Comment by meteorcloudy** [comment]
@Androbin Thanks for your change, but we don't merge PR on this repository. Can you send a change on gerrit?  https://bazel-review.googlesource.com/#/admin/projects/continuous-integration
```
git clone https://bazel.googlesource.com/continuous-integration && (cd continuous-integration && curl -Lo `git rev-parse --git-dir`/hooks/commit-msg https://gerrit-review.googlesource.com/tools/hooks/commit-msg ; chmod +x `git rev-parse --git-dir`/hooks/commit-msg)
...Commit your change...
git push https://bazel.googlesource.com/continuous-integration HEAD:refs/for/master
```

**Comment by Androbin** [comment]
Thanks for the redirect @meteorcloudy 
https://bazel-review.googlesource.com/c/11951/

**Pull request closed without merging**
