### PR TITLE
Set TF_IGNORE_MAX_BAZEL_VERSION=1

### PR DESCRIPTION
**Pull request by meteorcloudy**
This avoid breaking TensorFlow pipeline on Bazel CI every time when we have a new release

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Testing at https://buildkite.com/bazel/pcloudy-test/builds/52

**Comment by philwo** [comment]
What about using our environment variable feature to set it? That should work, too and looks nice. :)

https://github.com/bazelbuild/continuous-integration/tree/master/buildkite#setting-environment-variables

**Comment by meteorcloudy** [comment]
@philwo That is super nice!

**Comment by meteorcloudy** [comment]
Hmm, when I set the value to `true` or `"true"`, I got:
```
```

**Comment by meteorcloudy** [comment]
When using `1`, I got
```

$ /bin/sh -e -c 'curl -sS https://raw.githubusercontent.com/bazelbuild/continuous-integration/master/buildkite/bazelci.py?1558703322 -o bazelci.py
--
  | python3.6 bazelci.py runner --task=ubuntu1804 --http_config=https://raw.githubusercontent.com/bazelbuild/continuous-integration/meteorcloudy-patch-1/buildkite/pipelines/tensorflow-postsubmit.yml'
  | Traceback (most recent call last):
  | File "bazelci.py", line 2647, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 2627, in main
  | bazel_version=task_config.get("bazel") or configs.get("bazel"),
  | File "bazelci.py", line 711, in execute_commands
  | os.environ.update(task_config.get("environment", {}))
  | File "/usr/lib/python3.6/_collections_abc.py", line 841, in update
  | self[key] = other[key]
  | File "/usr/lib/python3.6/os.py", line 674, in __setitem__
  | value = self.encodevalue(value)
  | File "/usr/lib/python3.6/os.py", line 744, in encode
  | raise TypeError("str expected, not %s" % type(value).__name__)
  | TypeError: str expected, not int


```
on Windows and Linux, but not mac...

**Comment by meteorcloudy** [comment]
After 4ad4aac7a6e7dee5007997d62221c015672578e9 and 5c7ea41f21024d8c8522eb0fa7e689c6e30b4c9a it's working!
https://buildkite.com/bazel/pcloudy-test/builds/59

**Pull request merged**
