### PR TITLE
Enable rules_foreign_cc with downstream Bazel; the build is green.

### PR DESCRIPTION
**Pull request by irengrig**

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Thanks!

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/655#00e3540f-e74c-4453-acda-e40416525e9c
@irengrig It is red with Bazel@HEAD, please fix ;)
```

ERROR: /var/lib/buildkite-agent/builds/bk-worker-ubuntu1804-java8-4xkx/bazel-downstream-projects/rules_foreign_cc/examples/cmake_hello_world_lib/shared/BUILD:12:1: in cmake_external rule //examples/cmake_hello_world_lib/shared:libhello:
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/bk-worker-ubuntu1804-java8-4xkx/bazel-downstream-projects/rules_foreign_cc/examples/cmake_hello_world_lib/shared/BUILD", line 12
  | cmake_external(name = 'libhello')
  | File "/var/lib/buildkite-agent/builds/bk-worker-ubuntu1804-java8-4xkx/bazel-downstream-projects/rules_foreign_cc/tools/build_defs/cmake.bzl", line 34, in _cmake_external
  | cc_external_rule_impl(ctx, attrs)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/02e1fdcd6d7f9d9349cd25b094623780/external/foreign_cc_impl/framework.bzl", line 213, in cc_external_rule_impl
  | _correct_path_variable(get_env_vars(ctx))
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/02e1fdcd6d7f9d9349cd25b094623780/external/foreign_cc_impl/framework.bzl", line 213, in _correct_path_variable
  | get_env_vars(ctx)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/02e1fdcd6d7f9d9349cd25b094623780/external/foreign_cc_impl/cc_toolchain_util.bzl", line 217, in get_env_vars
  | vars.update(cc_common.get_environment_variab...)))
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/02e1fdcd6d7f9d9349cd25b094623780/external/foreign_cc_impl/cc_toolchain_util.bzl", line 217, in vars.update
  | cc_common.get_environment_variables(feature_configuration = feature_..., <2 more arguments>)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/02e1fdcd6d7f9d9349cd25b094623780/external/foreign_cc_impl/cc_toolchain_util.bzl", line 220, in cc_common.get_environment_variables
  | cc_common.create_compile_variables(feature_configuration = feature_..., <2 more arguments>)
  | Passing depset into user flags is deprecated (see --incompatible_disable_depset_in_cc_user_flags), use list instead.


```

**Comment by irengrig** [comment]
Will do, thank you!

**Comment by irengrig** [comment]
Done! It's green! :))

**Comment by meteorcloudy** [comment]
Awesome!

**Pull request merged**
