### PR TITLE
Add platforms;android-28 and build-tools;28.0.2 to the Android SDK

### PR DESCRIPTION
**Pull request by jin**
The Android testing pipeline is now using these tools and APIs.

Fixes https://github.com/googlesamples/android-testing/issues/199

cc @brettchabot @mhlopko

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Hi @jin , can you rebase the branch and try to merge this change. It will make our CI greener! ;)

**Comment by jin** [comment]
Done, but waiting for @philwo for review.

**Comment by philwo** [comment]
I’ll build new images tomorrow.

**Comment by meteorcloudy** [comment]
@jin @philwo Thank you!

**Comment by meteorcloudy** [comment]
If we upgrade our CI machines for Android SDK, we'll have our downstream job green for the first in history! ;)

https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/483

**Comment by jin** [comment]
@meteorcloudy WOW! That's amazing!

**Comment by philwo** [comment]
Building new images now!

**Comment by philwo** [comment]
New Android SDK components have been installed on all iMac Pros.

**Comment by philwo** [comment]
@jin @meteorcloudy Installing the Android SDK is the step that takes the most time by far when creating a new image...

Can we remove some of the older platforms?

```
  "platforms;android-24" \
  "platforms;android-25" \
  "platforms;android-26" \
  "platforms;android-27" \
```

**Comment by meteorcloudy** [comment]
Thank you, both!

**Pull request merged**
