### PR TITLE
Add nojdk artifacts for Windows

### PR DESCRIPTION
**Pull request by JayBazuzi**
See https://github.com/bazelbuild/bazel/issues/13779

### CODE REVIEW

**Comment by JayBazuzi** [comment]
Tagging @meteorcloudy, per Konstantin Erman's suggestion.

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
Thanks!

**Comment by JayBazuzi** [comment]
Excellent!

@meteorcloudy Can you tell me whether this will impact Bazel 4.* or only Bazel 5?

We are currently blocked from upgrading to Bazel 5 because we depend on `--noincompatible_blacklisted_protos_requires_proto_info`. (We're working to remove that dependency but it will take a long time.)

**Comment by meteorcloudy** [comment]
We just had the 4.2.0 release, but looks like there will be a [4.2.1 release](https://github.com/bazelbuild/bazel/issues/13558#issuecomment-903872297) soon, which will use the updated release pipeline. So yes, the next Bazel release should include the nojdk version for Windows.

**Pull request merged**
