### PR TITLE
Always use `--experimental_worker_for_repo_fetching=platform` in baze…

### PR DESCRIPTION
**Pull request by Wyverald**
…l CI

### CODE REVIEW

**Comment by fweikert** [comment]
What's the reason for not using this flag?

**Comment by Wyverald** [comment]
I'll do a test run first :) https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1545#0188a0c5-9a90-4a75-b74c-f94948ab2221

**Comment by meteorcloudy** [comment]
The pipeline first runs tests without any incompatible flags. Does changing the value of `--experimental_worker_for_repo_fetching` cause the repo to be re-fetched? If not, you'll need to set `BAZELISK_CLEAN=1` to actually test it.

If this works fine, I'll prefer to just flip this at HEAD instead of enabling it in CI scripts.

**Comment by Wyverald** [comment]
I re-ran the incompatible platform with `BAZELISK_CLEAN=1`, and confirmed that `bazel clean --expunge` is run before the invocation with `--experimental_worker_for_repo_fetching=platform`. I'll send a change to enable it on HEAD.

**Pull request closed without merging**
