### PR TITLE
Add a new target to mirror tensorflow dependencies on bazel mirror.

### PR DESCRIPTION
**Pull request by gunan**
@damienmg @jart I finally got around to creating the targets for mirroring TF external dependencies.
I ran some simple tests, which seem to be OK.

The python code is 99% copied from Justine's scripts with some slight modifications. I left unit tests out, but Damien if you are running CI on this repository I can add the unit tests, too?
Please let me know if we need anything else here.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by damienmg** [comment]
Hi Gunan, would you mind sending it to gerrit, this repo does not accept
PR...

**Comment by damienmg** [comment]
(also sure, please include tests, we do test this repo).

**Comment by gunan** [comment]
All done, closing in favor of https://bazel-review.googlesource.com/c/12732/

**Pull request closed without merging**
