### PR TITLE
Gerrit unflip enable bzlmod option

### PR DESCRIPTION
**Pull request by davido**

### CODE REVIEW

**Comment by davido** [comment]
Actually this shouldn't be needed, once this [CL](https://gerrit-review.googlesource.com/c/gerrit/+/393394) is merged.

**Review by meteorcloudy — APPROVED** [review]

**Comment by davido** [comment]
@meteorcloudy 

Turns out SSH and Git Protocol V2 tests require some special setting, that complicate thing on Bazel CI, see:
https://buildkite.com/bazel/gerrit/builds/12701#018bfdc5-4521-4eb1-b4c5-8771b19b5617

I think it's much simpler to take those tests out of the picture, as trying to fix them.
I've sent this [CL](https://github.com/bazelbuild/continuous-integration/pull/1814) for review.

Could you please review it? Thanks!

**Comment by davido** [comment]
@meteorcloudy we clarified the problem with `openssh-client`.

Could you please look at RBE build breakage? I'm not sure I understand it:

https://buildkite.com/bazel/gerrit/builds/12729#018c15cd-c426-46d9-a8b0-a79c4924240c

It seems, that outdated options pulled in on this platform?
I don't know how/where to fix it?

Should we try to fix it, or should I removed RBE-platform again on Bazel-CI@Buildkite.

We are using RBE@GCP downstream without any issue for years now...

**Comment by meteorcloudy** [comment]
It's from the bazelci.py script, there is some recent change to update the flag names, but was rollbacked for some reason. @fweikert 
https://github.com/bazelbuild/continuous-integration/pull/1811

The logic is here: https://github.com/bazelbuild/continuous-integration/blob/387688afe2943c80799990a22601527bf671b507/buildkite/bazelci.py#L2027-L2034

**Comment by davido** [comment]
@meteorcloudy Thanks for the pointer. I will file an issue for this platform and will remove it for now for gerrit pipeline, and reconsider to re-add the build on RBE platform later, once it's fixed.

**Pull request merged**
