### PR TITLE
Disable Cloud Robotics Core in downstream

### PR DESCRIPTION
**Pull request by meteorcloudy**
Due to https://github.com/googlecloudrobotics/core/issues/13

### CODE REVIEW

**Comment by meteorcloudy** [comment]
A fix from Cloud Robotics Core is waiting to be submitted. Maybe we don't have to disable it. Please don't merge yet.

**Comment by meteorcloudy** [comment]
The issue is now fixed!

**Comment by fweikert** [comment]
Yun, thank you for taking care of this issue!

**Comment by meteorcloudy** [comment]
No problem!

**Pull request closed without merging**
