### PR TITLE
Added jingwen@ to Jenkins admin list

### PR DESCRIPTION
**Pull request by jin**

### CODE REVIEW

**Comment by katre** [comment]
Changes for this repository need to go through Gerrit. Follow the directions at https://bazel.build/contributing.html, except push to https://bazel.googlesource.com/continuous-integration instead of https://bazel.googlesource.comb/bazel.

**Comment by jin** [comment]
Gotcha, thanks.

**Comment by jin** [comment]
@katre It looks like this repository has bidirectional syncing: https://github.com/bazelbuild/continuous-integration/blob/bce8f35f4548bf22ffd499dc96352e780f40df37/gerrit-github-sync/gerrit-github-sync.sh#L25

There are also merged PRs: https://github.com/bazelbuild/continuous-integration/pulls?q=is%3Apr+is%3Aclosed

**Comment by jin** [comment]
Closing this since there's a Gerrit change for this.

**Pull request closed without merging**
