### PR TITLE
Fedora39 platform

### PR DESCRIPTION
**Pull request by davido**
Fixes: https://github.com/bazelbuild/continuous-integration/issues/1593.

Closes: #1639.

### CODE REVIEW

**Comment by meteorcloudy** [comment]
I have pushed `gcr.io/bazel-public/fedora39-java17` and `gcr.io/bazel-public/fedora39-bazel-java17` so this should work

**Comment by davido** [comment]
> Please rebase

Done.

> I have pushed gcr.io/bazel-public/fedora39-java17 and gcr.io/bazel-public/fedora39-bazel-java17 so this should work

Great, thanks!

**Comment by meteorcloudy** [comment]
You probably want to drop the merged commits

**Comment by davido** [comment]
>> You probably want to drop the merged commits

> Working on it.

Done

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
