### PR TITLE
UNDO THIS: add debug logging to bazel-release.yml

### PR DESCRIPTION
**Pull request by laszlocsomor**
Context: https://github.com/bazelbuild/continuous-integration/pull/745#issuecomment-510532253

Fix that culprit and undo this commit.

### CODE REVIEW

**Comment by laszlocsomor** [comment]
cc @philwo

**Comment by fweikert** [comment]
You need to request a merge into "testing", not "master" since your PR contains some of our older testing commits.

**Comment by laszlocsomor** [comment]
Thanks @philwo and @fweikert . How do I request that next time?

**Comment by fweikert** [comment]
When you open the PR you can select the target branch at the top.

**Comment by philwo** [comment]
Thanks!

**Comment by philwo** [comment]
Running the test build again here: https://buildkite.com/bazel-testing/bazel-release/builds/2#b54335d8-6676-43ac-bbb4-b03f87af14a6

**Comment by philwo** [comment]
@laszlocsomor The failing command is:

d:\b\bk-testing-windows-java8-1cnd\bazel-testing\bazel-release>git merge-base --is-ancestor 874fe754282651bdf006c06147842cbb226c6ae9 HEAD  2>nul

Because we redirect its stderr to NUL we don't see the error message (we shouldn't do this, I had the same issue when debugging the failing Windows build yesterday).

What I think happens here is that git can't find the ancestor commit and exits with error code 1, but because Buildkite implicitly checks the errorlevel after every command (see the bunch of `if 1 NEQ 0 exit /b 1` lines in the log), the job then fails even though we do our own error handling a line below.

Any idea how to workaround this?

**Comment by laszlocsomor** [comment]
Thanks. We can wrap the git command in a `.bat` file that prints `y` or `n`. WDYT?

**Comment by philwo** [comment]
@laszlocsomor Yeah, let's try that. Good idea!

**Pull request merged**
