### PR TITLE
Add support for bazel coverage

### LINKED ISSUE #1171: Support coverage_targets
It would be nice to support coverage_targets in the same way that there is run_targets and build_targets

### PR DESCRIPTION
**Pull request by limdor**
Resolved #1171

### CODE REVIEW

**Comment by limdor** [comment]
I strated sketching some proposal to support bazel coverage. I have some open questions like:
- Should it support bep file?
- Should it rerun flaky tests?
My goal was if we could at least have a basic implementation of bazel coverage, without it is a bit harder to work on example to show the current status of bazel coverage. It can be done but then bazel continuous-integration cannot be used.

**Comment by meteorcloudy** [comment]
Thanks! Can you also add some documentation here: https://github.com/bazelbuild/continuous-integration/tree/master/buildkite#configuring-a-pipeline?

**Comment by limdor** [comment]
Done

**Review by meteorcloudy — APPROVED** [review]
Thank you!

**Pull request merged**
