### PR TITLE
Mention new Homebrew package location in playbook

### PR DESCRIPTION
**Pull request by philwo**
FYI @chenrui333

### CODE REVIEW

**Comment by philwo** [comment]
@katre @meisterT @laurentlb Could someone of you please review this?

**Comment by chenrui333** [comment]
Another interesting thought is if we are OK to introduce some Github Action flow (or CI flow) to auto-bump the version.

**Comment by philwo** [comment]
> Another interesting thought is if we are OK to introduce some Github Action flow (or CI flow) to auto-bump the version.

I haven't used GitHub Actions yet, but that sounds interesting. Any idea how we would set this up?

**Comment by chenrui333** [comment]
> > Another interesting thought is if we are OK to introduce some Github Action flow (or CI flow) to auto-bump the version.
> 
> I haven't used GitHub Actions yet, but that sounds interesting. Any idea how we would set this up?

Totally, it is actually very simple and easy. This is some reference PR ( `https://github.com/terraform-linters/tflint/pull/684` )
I can take on some initiative on this, but I will need a token (repo token) to make it actually work.

**Pull request merged**
