### PR TITLE
Install platforms;android-31

### PR DESCRIPTION
**Pull request by Bencodes**
https://github.com/bazelbuild/continuous-integration/issues/1363

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Can you please update https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/setup-docker.sh#L192 as well, the `buildkite/android.sh` doesn't seem to be used now.

**Comment by Bencodes** [comment]
Added API 31 to `buildkite/setup-docker.sh` as well.

**Comment by meteorcloudy** [comment]
Sorry, also the Windows script needs to be updated: https://github.com/bazelbuild/continuous-integration/blob/cd98080c0ff7ac24df333383121cc5ad6cb67965/buildkite/setup-windows.ps1#L235

**Comment by meteorcloudy** [comment]
After this PR is merged, we'll need to re-deploy the Linux docker containers and update the mac machines.

**Comment by Bencodes** [comment]
Updated the last setup as well. Thanks for the review!

**Review by meteorcloudy — APPROVED** [review]
Thanks!

**Comment by Bencodes** [comment]
@meteorcloudy have you been able to deploy these changes yet?

**Comment by meteorcloudy** [comment]
Sorry for the delay, I just deployed the change the our Linux VMs, https://github.com/bazelbuild/rules_kotlin/pull/722 is now passing.

**Pull request merged**
