### PR TITLE
Integrate chocolatey build and push to release pipeline

### PR DESCRIPTION
**Pull request by keertk**
Issue: https://github.com/bazelbuild/continuous-integration/issues/1456

One successful run (without choco push): https://buildkite.com/bazel-trusted/bazel-release/builds/1149#0187e4f2-cde0-43c8-b4ef-4c250c053249

```
StatusCode        : 200
StatusDescription : OK
Content           : {53, 51, 52, 51...}
RawContent        : HTTP/1.1 200 OK
                    X-GUploader-UploadID: ADPycdukvqcJCd4f9KE2dONfu7OoJ-rkJAcXSwFNDbU8tnv9bSE_YzaESHqyOL4OkcEkp-4Uatv1_
                    0uJYJRztxp4Lr9fw0XXqIoJ
                    x-goog-generation: 1682371417868867
                    x-goog-metageneration:...
Headers           : {[X-GUploader-UploadID, ADPycdukvqcJCd4f9KE2dONfu7OoJ-rkJAcXSwFNDbU8tnv9bSE_YzaESHqyOL4OkcEkp-4Uatv
                    1_0uJYJRztxp4Lr9fw0XXqIoJ], [x-goog-generation, 1682371417868867], [x-goog-metageneration, 1],
                    [x-goog-stored-content-encoding, identity]...}
RawContentLength  : 100
 
Copying LICENSE from repo-root to tools directory
Chocolatey v1.2.1
Attempting to build package from 'bazel.nuspec'.
Successfully created package 'C:\b\bk-trusted-windows-15c6\bazel-trusted\bazel-release\scripts\packages\chocolatey\bazel.6.2.0-rc1.nupkg'
```

### CODE REVIEW

**Comment by meteorcloudy** [comment]
/cc @petemounce Do you think it's fine to also push release candidates to choco? Looks like the script does support that
https://github.com/bazelbuild/bazel/blob/master/scripts/packages/chocolatey/build.ps1#L12-L29

**Comment by petemounce** [comment]
[Yup](https://community.chocolatey.org/packages/bazel/1.0.0-rc4)!

**Review by meteorcloudy — APPROVED** [review]
Thanks!

**Comment by fweikert** [comment]
Is it WAI that this code runs for rolling releases, too? https://buildkite.com/bazel-trusted/bazel-release/builds?branch=release-7.0.0-pre.20230502.1rc1

**Comment by keertk** [comment]
@fweikert thanks for pointing this out - didn't realize rolling releases would also be affected. I'll update.

**Comment by petemounce** [comment]
I believe if the version strings are semver, chocolatey will deal with those fine. Users who add `--pre` to their install command will get the latest pre-release.

**Pull request merged**
