### PR TITLE
Publish bazelbuild/bazel site sources to docs.bazel.build.

### PR DESCRIPTION
**Pull request by davidzchen**

### CODE REVIEW

**Comment by davidzchen** [comment]
Please let me know if there are other changes that I need to make. Based on what I read from [`jenkins/jobs/global.groovy`](https://github.com/bazelbuild/continuous-integration/blob/f67b866bb62dc67be4ce3e66868ca86714c1031e/jenkins/jobs/global.groovy) and [`jenkins/jobs/jobs-Bazel-Publish-Site.xml.tpl`](https://github.com/bazelbuild/continuous-integration/blob/2493d3af196cf01fae1afdc1b94a5f3e73e2421a/jenkins/jobs/jobs-Bazel-Publish-Site.xml.tpl), the bucket name is extracted from the name of the tarball.

**Comment by damienmg** [comment]
You need also to change scripts/ci/build.sh on Bazel side (this change only the new pipeline which is not yet ready). Also on this repo we can only accept change on gerrit (though we could change that).

**Comment by davidzchen** [comment]
Sent the following review: https://bazel-review.googlesource.com/c/11568/

**Comment by damienmg** [comment]
Was merged on gerrit

**Pull request closed without merging**
