### PR TITLE
Enable TensorFlow on macos

### PR DESCRIPTION
**Pull request by meteorcloudy**

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Unfortunately the build on macos failed due to https://github.com/bazelbuild/bazel/issues/7607 https://buildkite.com/bazel/tensorflow/builds/2410#5888e757-f673-4295-a3cf-922ae3d7026d

**Comment by meteorcloudy** [comment]
Looks like we need to install some python pip package for the TF build
https://buildkite.com/bazel/tensorflow/builds/2416#2dfab2a4-a599-4b80-9e34-69d398944f67
```
ImportError: No module named enum
```
https://www.tensorflow.org/install/source

**Comment by meteorcloudy** [comment]
@fweikert Can you help install pip packages required by TensorFlow on our Mac machines?
```
pip install -U --user pip six numpy wheel setuptools mock
pip install -U --user keras_applications==1.0.6 --no-deps
pip install -U --user keras_preprocessing==1.0.5 --no-deps
```

**Comment by philwo** [comment]
@meteorcloudy Can we do this for Tensorflow in the "setup_script" phase of the pipeline?

I would rather not add more project-specific dependencies to the machines... we can do it, if there's no better way, but it's error-prone to maintain.

**Comment by meteorcloudy** [comment]
@philwo Sounds good, let me try that.

**Comment by philwo** [comment]
Can we enable this now? :)

**Comment by meteorcloudy** [comment]
Testing at https://buildkite.com/bazel/pcloudy-test/builds/45

**Comment by meteorcloudy** [comment]
```
Collecting keras_preprocessing==1.0.5

  Downloading https://files.pythonhosted.org/packages/fc/94/74e0fa783d3fc07e41715973435dd051ca89c550881b3454233c39c73e69/Keras_Preprocessing-1.0.5-py2.py3-none-any.whl

Installing collected packages: keras-preprocessing

Successfully installed keras-preprocessing-1.0.5
```
Looks like the pip package is installed, but the build still failed on macos with
```
ImportError: No module named keras_preprocessing
```

**Comment by philwo** [comment]
Which Python version is Bazel / Tensorflow using? The `pip` commands should install the packages for Python 3, but maybe it's using the system-provided Python 2.7?

**Comment by meteorcloudy** [comment]
Oh, yes, it's using Python 2.7

**Comment by meteorcloudy** [comment]
Can you tell me the Python 3 path on our mac machine?

**Comment by philwo** [comment]
Yes, that should be:

/usr/local/bin/python3

**Comment by meteorcloudy** [comment]
After using python3, it is working!
https://buildkite.com/bazel/pcloudy-test/builds/47#_

**Comment by philwo** [comment]
NICE! Congrats and thanks, Yun! :))

**Pull request merged**
